/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ema.gltf -t -T 
Files: ema.gltf [200.1KB] > C:\Users\Ema\Desktop\ema-transformed.glb [197.22KB] (1%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRef } from "react";

type GLTFResult = GLTF & {
    nodes: {
        mmGroup0: THREE.Mesh;
    };
    materials: {};
};

export default function Ema(props: JSX.IntrinsicElements["group"]) {
    //loads the model
    const { nodes } = useGLTF("/3d/ema-transformed.glb") as GLTFResult;

    const mesh = useRef<THREE.Mesh>(null!);

    return (
        <group
            {...props}
            dispose={null}
            scale={[0.2, 0.2, 0.2]}
            rotation={[0, -Math.PI / 2, -0.2]}>
            <mesh
                ref={mesh}
                geometry={nodes.mmGroup0.geometry}
                material={new THREE.MeshLambertMaterial({ color: 0xe0e0e0 })}
            />
        </group>
    );
}

useGLTF.preload("/ema-transformed.glb");
